--luaGeneratorOutput.lua
--Generated by Matthew Sweeney's generator for shawzin Logitech macros

n=2700

function OnEvent(event, arg)
    if (event == "MOUSE_BUTTON_RELEASED" and arg == 6) then
        play1()
        Sleep(5)
        ReleaseKey("x", "y", "up", "down", "left", "right", "1", "2", "3")
        for i = 1, 3, 1 do
            ReleaseMouseButton(i)
            Sleep(5)
        end
        OutputLogMessage("Done\n")
    end
end

function tabn(_n)
    Sleep(2)
    for i = 1, _n, 1 do  -- Tab n times, waiting 2ms in between
        PressAndReleaseKey("tab")
        Sleep(2)
    end
end

function qtabn(_n)  -- Quick version
    Sleep(1)
    for i = 1, _n, 1 do
        PressAndReleaseKey("tab")
        Sleep(1)
    end
end

function switch_mouse(from, to)
    if from > 0 then
        ReleaseMouseButton(from)
    end
    if to > 0 then
        PressMouseButton(to)
    end
end

function play1()
    Sleep(0*n)
    qtabn(0)
    switch_mouse(0, 0)
    Sleep(1)
end