--luaGeneratorOutput.lua
--Generated by Matthew Sweeney's generator for shawzin Logitech macros

n=2700

function OnEvent(event, arg)
    if (event == "MOUSE_BUTTON_RELEASED" and arg == 6) then
        play1()
        Sleep(5)
        ReleaseKey("x", "y", "up", "down", "left", "right", "1", "2", "3")
        for i = 1, 3, 1 do
            ReleaseMouseButton(i)
            Sleep(5)
        end
        OutputLogMessage("Done\n")
    end
end

function tabn(_n)
    Sleep(2)
    for i = 1, _n, 1 do  -- Tab n times, waiting 2ms in between
        PressAndReleaseKey("tab")
        Sleep(2)
    end
end

function qtabn(_n)  -- Quick version
    Sleep(1)
    for i = 1, _n, 1 do
        PressAndReleaseKey("tab")
        Sleep(1)
    end
end

function switch_mouse(from, to)
    if from > 0 then
        ReleaseMouseButton(from)
    end
    if to > 0 then
        PressMouseButton(to)
    end
end

function play1()
    Sleep(0*n)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --C6
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --F4
    Sleep(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --C5
    Sleep(1)
    Sleep(0.0625*n)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --F4
    Sleep(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --C6
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --F4
    Sleep(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --C5
    Sleep(1)
    Sleep(0.0625*n)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --F4
    Sleep(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(2)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --G#4
    Sleep(1)
    Sleep(0.0625*n)
    Sleep(1)
    PressAndReleaseKey("3")  --G#4
    Sleep(1)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    qtabn(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("1")  --E5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --F4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --C5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    qtabn(4)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --G4
    Sleep(1)
    qtabn(2)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(2)
    switch_mouse(0, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    Sleep(0.0625*n)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    qtabn(4)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --G#4
    Sleep(1)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --F4
    Sleep(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --C5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(2)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    qtabn(4)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --G#4
    Sleep(1)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(1)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("1")  --B4
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --F4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --D5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(5)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("3")  --B4
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --G#4
    Sleep(1)
    qtabn(1)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(2)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("1")  --F4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --D5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("1")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("3")  --A-4
    Sleep(1)
    switch_mouse(1, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --C6
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("3")  --G5
    Sleep(1)
    qtabn(2)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --D4
    Sleep(1)
    qtabn(2)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --D4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("3")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --C6
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("3")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(2)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --D4
    Sleep(1)
    qtabn(2)
    switch_mouse(0, 2)
    Sleep(1)
    PressAndReleaseKey("3")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 1)
    Sleep(1)
    PressAndReleaseKey("2")  --G4
    Sleep(1)
    switch_mouse(1, 2)
    Sleep(1)
    PressAndReleaseKey("2")  --E-5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(2, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("2")  --D4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --F5
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(1)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("3")  --E-4
    Sleep(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("3")  --G5
    Sleep(1)
    Sleep(0.0625*n)
    switch_mouse(3, 0)
    Sleep(1)
    PressAndReleaseKey("1")  --C4
    Sleep(1)
    qtabn(1)
    switch_mouse(0, 3)
    Sleep(1)
    PressAndReleaseKey("2")  --C6
    Sleep(1)
    Sleep(0.0625*n)
    qtabn(2)
    switch_mouse(3, 0)
    Sleep(1)
end
